### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by maartenpaauw** [home-assistant-community-themes/aqua-fiesta#2]
**TODO**

- [x] Theme filename needs `_` instead of `-`.
	- [x] The same for the theme key.
- [x] Screenshot extension to lowercase.
